property/urls.py
from django.urls import re_path,path

from . import views
from .views import signup_view



app_name = 'property'


urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^delete/property/(?P<id>\d+)/', views.delete_property, name='property'),
    re_path(r'^delete/landlord/(?P<id>\d+)/', views.delete_landlord, name='landlord'),
    re_path(r'^delete/tenant/(?P<id>\d+)/', views.delete_tenant, name='tenant'),
    re_path(r'^delete/unit/(?P<id>\d+)/', views.delete_unit, name='unit'),
    re_path(r'^delete/transferred/tenant/(?P<id>\d+)/', views.delete_transfer, name='transfer'),
    re_path(r'^delete/checked/out/tenant/(?P<id>\d+)/', views.delete_checkout, name='checkout'),
    re_path(r'^delete/rent/(?P<id>\d+)/', views.delete_rent, name='rent'),
    re_path(r'^delete/expense/(?P<id>\d+)/', views.delete_expense, name='expense'),
    path('delete/damage/<int:id>',views.delete_damage,name='delete_damage'),
    path('delete/checked_tenants/<int:id>',views.delete_checked_tenant,name='delete_cheked'),
    re_path(r'^edit/expense/(?P<id>\d+)/', views.edit_expense, name='edit_expense'),
    re_path(r'^edit/property/(?P<id>\d+)/', views.edit_property, name='edit_property'),
    re_path(r'^edit/landlord/(?P<id>\d+)/', views.edit_landlord, name='edit_landlord'),
    re_path(r'^edit/tenant/(?P<id>\d+)/', views.edit_tenant, name='edit_tenant'),
    re_path(r'^edit/unit/(?P<id>\d+)/', views.edit_unit, name='edit_unit'),
    re_path(r'^edit/transfer/tenant/(?P<id>\d+)/', views.edit_transfer, name='edit_transfer'),
    re_path(r'^edit/checkout/(?P<id>\d+)/', views.edit_checkout, name='edit_checkout'),
    re_path(r'^edit/rent/(?P<id>\d+)/', views.edit_rent, name='edit_rent'),
    path('edit/damage/<int:id>',views.edit_damage,name='edit_damage'),
    path('property/<int:pk>/', views.PropertyDetail.as_view(), name='property_detail'),
    path('unit/<int:pk>/', views.UnitDetail.as_view(), name='unit_detail'),
    path('landlord/<int:pk>/', views.LandlordDetail.as_view(), name='landlord_detail'),
    path('tenant/<int:pk>/', views.TenantDetail.as_view(), name='tenant_detail'),
    path('transferedtenants/<int:pk>/', views.Transfered_TenantDetail.as_view(), name='transferedtenants_detail'),
    path('checkouttenants/<int:pk>/', views.UnitDetail.as_view(), name='checkouttenants_detail'),
    path('rent/<int:pk>/', views.RentDetail.as_view(), name='rent_detail'),
    path('expenses/<int:pk>/', views.ExpenseDetail.as_view(), name='expense_detail'),
    re_path('signup/',views.signup_view, name="signup"),
    re_path(r'^detailed/property/(?P<id>\d+)/', views.detailed_property_report, name='detailed_property_report'),
    re_path(r'^detailed/property/rent/(?P<id>\d+)/', views.detailed_property_rent, name='detailed_property_rent'),
    re_path(r'^add/rent/(?P<id>\d+)/', views.add_rent, name='add_rent'),
    re_path(r'^detailed/property/landlord/(?P<id>\d+)/', views.detailed_property_landlord, name='detailed_property_landlord'),
    re_path(r'^add/landlord/(?P<id>\d+)/', views.add_landlord, name='add_landlord'),
    re_path(r'^detailed/property/tenant/(?P<id>\d+)/', views.detailed_property_tenant, name='detailed_property_tenant'),
    re_path(r'^add/tenant/(?P<id>\d+)/', views.add_tenant, name='add_tenant'),
    re_path(r'^detailed/property/transfer/(?P<id>\d+)/', views.detailed_property_transfer, name='detailed_property_transfer'),
    re_path(r'^add/transfer/(?P<id>\d+)/', views.add_transferred_tenant, name='add_transfer'),
    re_path(r'^detailed/property/checkout/(?P<id>\d+)/', views.detailed_property_checkout, name='detailed_property_checkout'),
    re_path(r'^add/checkout/(?P<id>\d+)/', views.add_checkout, name='add_checkout'),
    path('unit/rent/<int:id>',views.rent_detail,name='single_unit_rent'),
    path('fin/statement/<int:id>',views.property_financial_statement,name='statement'),
    path('fin/statement/',views.property_financial_summary,name='summary_report'),
    path('dmages/<int:id>',views.single_tenant_damages,name='single-tenant-damages'),



]

property_management/urls.py
from django.contrib import admin
from django.urls import re_path, include,path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('allauth.urls')),
    re_path(r'^', include('property.urls', namespace='property')),
    path('chaining/', include('smart_selects.urls')),
    ]

property/forms.py
from django import forms
from .models import Property, Landlord, Tenant, Transfered_Tenant, Checked_out_Tenant, Rent, Expense, Unit, Messages,User, Damage
# from django.contrib.auth.models import User
from django.contrib import messages
from django.utils.dates import MONTHS
from django.core.validators import RegexValidator
from datetime import date
import datetime
from num2words import num2words
from django.core.validators import ValidationError
from django.core.exceptions import NON_FIELD_ERRORS
import calendar
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('name', 'code', 'location', 'number_of_units', 'number_of_floors')


class LandlordForm(forms.ModelForm):
    Phone = forms.CharField(min_length=10)

    class Meta:
        model = Landlord
        fields = ('name', 'id', 'ID_or_Passport', 'Phone')


class UnitForm(forms.ModelForm):

    class Meta:
        model = Unit
        fields = ('property', 'unit_number','type', 'floor_number', 'monthly_rent')


class TenantForm(forms.ModelForm):
    Phone = forms.CharField(min_length=10)

    class Meta:
        model = Tenant
        fields = ('name', 'id', 'ID_or_Passport', 'Phone', 'deposit_paid')






class TransferredTenantForm(forms.ModelForm):
    class Meta:
        model = Transfered_Tenant
        fields = ('new_unit', 'transfer_date')

    def __init__(self, *args, **kwargs):
        super(TransferredTenantForm, self).__init__(*args, **kwargs)
        try:
            self.fields['new_unit'].queryset = Unit.objects.filter(occupied=False)
        except Unit.DoesNotExist:
            ### there is not userextend corresponding to this user, do what you want
            raise Exception('object does not exist')
            pass


class CheckedOutTenantForm(forms.ModelForm):
    class Meta:
        model = Checked_out_Tenant
        fields = ('checked_out_date',)


class RentForm(forms.ModelForm):
    Reciept_no = forms.CharField(label='Receipt Number or Transaction ID',required = False)

    class Meta:
        model = Rent
        fields = ('rent', 'service_charge', 'month','year','date_paid', 'mode_of_payment', 'Reciept_no')






class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ('property_code', 'year','month','Description', 'Amount', 'Date')


class MessagesForm(forms.ModelForm):
    class Meta:
        model = Messages
        fields = ('send_to_all', 'tenant', 'message',)

    def __init__(self, *args, **kwargs):
        super(MessagesForm, self).__init__(*args, **kwargs)
        try:
            self.fields['tenant'].queryset = Tenant.objects.filter(active=True)
        except Unit.DoesNotExist:
            ### there is not userextend corresponding to this user, do what you want
            raise Exception('object does not exist')
            pass



class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=150, help_text='Email')

    class Meta:
        model = User
        fields = ('full_name' ,'email','phone' ,'password1','password2' )



class UserUpdateForm(UserChangeForm):
    email = forms.CharField(max_length=150, help_text='Email')

    class Meta:
        model = User
        fields = ('full_name' ,'email' )


class DamageForm(forms.ModelForm):

    class Meta:
        model = Damage
        exclude = ('id', 'recorded_by','date')

property/views.py
import re
import string
import os
import africastalking
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from django.contrib import messages
from .models import *
from django.views import generic
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.conf import settings
from .credentials import USERNAME, APIKEY
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
import calendar
from django.core.validators import ValidationError
from django.db import IntegrityError

from django.db.models import Sum, Count,Min
import datetime
from utils.helpers import send_sms








@login_required(login_url='/accounts/login/')
def home(request):
    properties = Property.objects.all()
    landlords = Landlord.objects.all()
    tenants = Tenant.objects.filter(active=True)
    units = Unit.objects.all()
    transferred_tenants = Transfered_Tenant.objects.all()
    checked_out_tenants = Checked_out_Tenant.objects.all()
    rents = Rent.objects.all()
    # debtors = Rent.objects.filter(Balance > 0)
    expenses = Expense.objects.all()
    message_ins = IbgaroMessageCounter.objects.get(name='admin')
    messages_count = message_ins.total_messages_sent
    properties_count = properties.count()
    landlords_count = landlords.count()
    tenants_count = tenants.count()
    units_count = units.count()
    transferred_count = transferred_tenants.count()
    checkedout_count = checked_out_tenants.count()
    rent_count = rents.count()
    expenses_count = expenses.count()
    allocated_message = Allocated_message.objects.get(name='admin')
    rem = allocated_message.count
    damages = Damage.objects.all()
    tenants_out = ChekedOutTenant.objects.all()
    property_form = None
    expense_form = None
    unit_form = None
    landlord_form = None
    tenant_form = None
    checkout_form = None
    transfer_form = None
    rent_form = None
    message_form = None
    damage_form = None
    # add property form
    if request.method == 'POST':
        if 'property_button' in request.POST:
            property_form = PropertyForm(data=request.POST)
            if property_form.is_valid():
                property_form.save()
                messages.success(request, "Property added successfully")
                return redirect('property:home')
            if property_form.is_valid() == False:
                property_form = PropertyForm(data=request.POST)
                messages.error(request, "Error adding property, code and name must be unique")
                return redirect('property:home')
    else:
        property_form = PropertyForm()

    # add Unit form
    if request.method == 'POST':
        checker = True
        if 'unit_button' in request.POST:
            unit_form = UnitForm(data=request.POST)
            if unit_form.is_valid():
                property_name = unit_form.cleaned_data['property']
                floor_number = unit_form.cleaned_data['floor_number']
                unit_number = unit_form.cleaned_data['unit_number']
                units = Unit.objects.all()
                for unit in units:
                    if unit.unit_number == unit_number and unit.property == property_name:
                        checker = False
                        messages.error(request, "That unit already exists")
                        unit_form = UnitForm()
                        return redirect('property:home')
                if checker:
                    unit_form.save()
                    messages.success(request, "Unit added successfully")
                    return redirect('property:home')
            else:
                messages.error(request, "Error adding unit")
    else:
        unit_form = UnitForm()

    #damages
    if request.method == 'POST':
        if 'damage_button' in request.POST:
            user = request.user
            damage_form = DamageForm(request.POST)
            if damage_form.is_valid():
                damage = damage_form.save(commit=False)
                damage.recorded_by = user
                damage.save()
                messages.success(request,"damage registered successfully")
                return redirect("property:home")
            else:
                messages.error(request,"Error adding damage")
                damage_form = DamageForm(request.POST)
                return render(request,'property/home.html',{"damage_form":damage_form})

    else:
        damage_form = DamageForm()

    # add LandLord form
    if request.method == 'POST':
        if 'landlord_button' in request.POST:
            landlord_form = LandlordForm(data=request.POST)
            if landlord_form.is_valid():
                unit_selected = landlord_form.cleaned_data['unit']
                unit_selected = str(unit_selected)
                unit_selected = unit_selected.split(' ', 1)[0]
                db_unit = Unit.objects.get(unit_number=unit_selected)
                db_unit.landlord_assigned = True
                db_unit.save()
                landlord_form.save()
                messages.success(request, "Landlord added successfully")
                return redirect('property:home')
            else:
                messages.error(request, "Error adding Landlord")
    else:
        landlord_form = LandlordForm()

    # add Tenant form
    if request.method == 'POST':
        if 'tenant_button' in request.POST:
            tenant_form = TenantForm(data=request.POST)
            if tenant_form.is_valid():
                selected_unit = tenant_form.cleaned_data['unit']
                selected_unit = str(selected_unit)
                selected_unit = selected_unit.split(' ', 1)[0]
                db_unit = Unit.objects.get(unit_number=selected_unit)
                phone = None
                for p in db_unit.unit_landlord.all():
                    phone = p.Phone

                db_unit.occupied = True
                db_unit.save()
                tenant_form.save()
                if phone != None:
                    # sms = africastalking.SMS
                    message = 'You have a new tenant in your house number {}'.format(
                        selected_unit)
                    cost = 0
                    m = len(message)
                    if m <= 144:
                        cost = 1
                    elif m <= 304:
                        cost = 2
                    elif m <= 464:
                        cost = 3
                    elif m <= 624:
                        cost = 4
                    elif m <= 784:
                        cost = 5
                    message_allocated = Allocated_message.objects.get(
                        name='admin')
                    counter = message_allocated.count
                    print(counter)
                    if cost < counter:
                        message_counter = IbgaroMessageCounter.objects.get(
                            name='admin')
                        message_counter.total_messages_sent = message_counter.total_messages_sent + 1
                        message_counter.save()
                        sender = 'softsearch'
                        response = send_sms(message, [phone])
                        counter = counter - cost
                        message_allocated.count = counter
                        message_allocated.save()
                        messages.success(request, "Tenant added successfully")
                    else:
                        messages.error(
                            request, "You dont have sufficent credit to send messages please recharge")
                else:
                    messages.success(request, "Tenant added successfully")

                return redirect('property:home')
            else:
                messages.error(
                    request, "Error adding tenant. Same name already exists. Name must be unique")
    else:
        tenant_form = TenantForm()

    # transferred tenant form
    if request.method == 'POST':
        if 'transfer_button' in request.POST:
            transfer_form = TransferredTenantForm(data=request.POST)
            if transfer_form.is_valid():
                tenant = transfer_form.cleaned_data['name']
                new_unit = transfer_form.cleaned_data['new_unit']
                new_transfer_form = transfer_form.save(commit=False)
                db_tenant = Tenant.objects.get(name=tenant)
                new_transfer_form.old_unit = db_tenant.unit
                db_tenant.unit.occupied = False
                db_tenant.unit.save()
                db_tenant.unit = new_unit
                db_tenant.unit.occupied = True
                db_tenant.unit.save()
                db_tenant.save()
                new_transfer_form.save()
                messages.success(request, "Tenant transferred successfully")
                return redirect('property:home')
            else:
                messages.error(request, "Error adding transferred tenant")
    else:
        transfer_form = TransferredTenantForm()
    # checkout tenant form
    if request.method == 'POST':
        if 'checkout_button' in request.POST:
            checkout_form = CheckedOutTenantForm(data=request.POST)
            if checkout_form.is_valid():
                tenant = checkout_form.cleaned_data['name']
                db_tenant = Tenant.objects.get(name=tenant)
                unit = db_tenant.unit
                try:
                    landlord = Landlord.objects.get(unit=unit)
                except Landlord.DoesNotExist:
                    landlord = None
                if landlord:
                    phone = landlord.Phone
                    new_check = checkout_form.save(commit=False)

property/templates/property/add_checkout.html
{% extends 'property/base.html' %}

{% block title %}Check Out Tenant {% endblock %}

{% block body %}
{% load crispy_forms_tags %}
{% if messages %}
{% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger">
    <strong>{{ message|escape }}</strong>
</div>
{% else %}
<div class="alert alert-success">
    <strong>{{ message|escape }}</strong>
</div>
{% endif %}
{% endfor %}
{% endif %}

<!--Add landlord start -->
<div class="tab-pane" id="tab-add-landlord">
    <div class="panel">
        <div class="panel-heading">
            <h2>Check Out Tenant</h2><br>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-10" style="margin:10px">
                    <form class="form-horizontal tabular-form" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {{checkout_form|crispy}}
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-sm-8 col-sm-10">
                                    <input name="checkout_button" type="submit" class="btn-primary btn"
                                           value="Confirm">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!--add landlord end-->

{% endblock %}

property/templates/property/add_tenant.html
{% extends 'property/base.html' %}

{% block title %}Add Tenant {% endblock %}

{% block body %}
{% load crispy_forms_tags %}
{% if messages %}
{% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger">
    <strong>{{ message|escape }}</strong>
</div>
{% else %}
<div class="alert alert-success">
    <strong>{{ message|escape }}</strong>
</div>
{% endif %}
{% endfor %}
{% endif %}

<!--Add landlord start -->
<div class="tab-pane" id="tab-add-landlord">
    <div class="panel">
        <div class="panel-heading">
            <h2>Add Tenant</h2><br>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-10" style="margin:10px">
                    <form class="form-horizontal tabular-form" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {{tenant_form|crispy}}
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-sm-8 col-sm-10">
                                    <input name="tenant_button" type="submit" class="btn-primary btn"
                                           value="Save">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!--add landlord end-->

{% endblock %}

property/templates/property/checkout_detail.html
{% extends 'property/base.html' %}
{% load static %}
{% block body %}


<div>
              <div class="row">
                <div class="col-md-8">
                    <section class="panel">
                        <div class="bio-graph-heading project-heading " style="background-color: #2a3542">
                            <strong> [  Checkedout  Tenants] </strong>
                        </div>
                        <div class="panel-body bio-graph-info">
                            <!--<h1>New Dashboard BS3 </h1>-->
                            <div class="row p-details">
                                <div class="bio-row">
                                    <h4><span class="bold">Property name </span>: {{ property.name }}</h4>
                                </div>
                                <div class="bio-row">
                                    <h4><span class="bold">Property Code</span>: {{ property.code }}</h4>
                                </div>
                                <div class="bio-row">
                                    <h4><span class="bold">Property location</span>:{{ property.location }}</h4>
                                </div>
                                <div class="bio-row">
                                    <h4><span class="bold">No of Units</span>:{{property.number_of_units}} </h4>
                                </div>
                                <div class="bio-row">
                                    <h4><span class="bold">No of floors </span>:{{property.number_of_floors}} </h4>
                                </div>
                                
                               

                                
                            </div>

                        </div>

                    </section>

                    

                </div>
                
            </div>
</div>
            {% endblock %}

property/templates/property/detailed_property_checkout.html
{% extends 'property/base_report.html' %}
{% block title %}Checkout Tenant{% endblock %}
{% block body %}

<div class="tab-pane" id="tab-display-expense">
    <!-- page start-->
    <section class="panel">
        <header class="panel-heading">
            Checkout Tenant
        </header>
        <table class="table table-hover p-table  responsive" width="100%" id="detailed_proper">
            <thead>
            <tr>
              <th>Property </th>
              <th>Landlord </th>
              <th>Tenant</th>
              <th>Unit number</th>
              <th>Floor number</th>
              <th>Monthly rent</th>
              <th>Occupied</th>
              <th>Add Tenant</th>
            </tr>
            </thead>
            <tbody>
            {% for r in units %}
            <tr>
                <td class="p-name">
                    <a>{{r.property}}</a>
                </td>
                {% for p in r.unit_landlord.all %}
                <td class="p-name">
                    <a>{{p.name}}</a>
                </td>
                {% empty %}
                <td class="p-name">
                    <a>Ibgaro</a>
                </td>
                {% endfor %}

                <td class="p-name">
                    <a>{{r.unit_tenant.name}}</a>
                </td>

                <td class="p-name">
                    <a>{{r.unit_number}}</a>
                </td>
                <td class="p-name">
                    <a>{{r.floor_number}}</a>
                </td>
                <td class="p-name">
                    <a>{{r.monthly_rent}}</a>
                </td>
                <td class="p-name">
                  {% if r.occupied %}
                       <a>occupied</a>
                  {% else %}
                       <a>vaccant</a>
                   {% endif %}
                </td>
                <td class="p-name">
                     <a href="{% url 'property:add_checkout'  r.id %}" class="btn btn-primary btn-xs"><i
                             class="fa fa-plus"></i> Checkout Tenant </a>
                </td>
                {% empty %}
                <td class="p-name">
                    <a>There are no matching prperty for your query </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>
    <!-- page end-->

</div>
{% endblock %}

property/templates/property/detailed_property_rent.html
{% extends 'property/base_report.html' %}
{% block title %}Add Rent{% endblock %}
{% block body %}

<div class="tab-pane" id="tab-display-expense">
    <!-- page start-->
    <section class="panel">
        <header class="panel-heading">
            Add Rent
        </header>
        <table class="table table-hover p-table  responsive" width="100%" id="detailed_proper">
            <thead>
            <tr>
              <th>Property </th>
              <th>Landlord </th>
              <th>Tenant</th>
              <th>Unit number</th>
              <th>Floor number</th>
              <th>Monthly rent</th>
              <th>Occupied</th>
              <th>Add rent</th>
            </tr>
            </thead>
            <tbody>
            {% for r in units %}
            <tr>
                <td class="p-name">
                    <a>{{r.property}}</a>
                </td>
                {% for p in r.unit_landlord.all %}
                <td class="p-name">
                    <a>{{p.name}}</a>
                </td>
                {% empty %}
                <td class="p-name">
                    <a>Ibgaro</a>
                </td>
                {% endfor %}
                {% if r.unit_tenant %}
                <td class="p-name">
                    <a>{{r.unit_tenant.name}}</a>
                </td>
                {% else %}
                <td class="p-name">
                    <a>Empty</a>
                </td>
                {% endif %}
                <td class="p-name">
                    <a>{{r.unit_number}}</a>
                </td>
                <td class="p-name">
                    <a>{{r.floor_number}}</a>
                </td>
                <td class="p-name">
                    <a>{{r.monthly_rent}}</a>
                </td>
                <td class="p-name">
                  {% if r.occupied %}
                       <a>occupied</a>
                  {% else %}
                       <a>vaccant</a>
                   {% endif %}
                </td>
                <td class="p-name">
                     <a href="{% url 'property:add_rent'  r.id %}" class="btn btn-primary btn-xs"><i
                             class="fa fa-plus"></i> Add Rent </a>
                </td>
                {% empty %}
                <td class="p-name">
                    <a>There are no matching prperty for your query </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>
    <!-- page end-->

</div>
{% endblock %}

property/templates/property/detailed_property_tenant.html
{% extends 'property/base_report.html' %}
{% block title %}Add Tenant{% endblock %}
{% block body %}

<div class="tab-pane" id="tab-display-expense">
    <!-- page start-->
    <section class="panel">
        <header class="panel-heading">
            Add Tenant
        </header>
        <table class="table table-hover p-table  responsive" width="100%" id="detailed_proper">
            <thead>
            <tr>
              <th>Property name </th>
              <th>Landlord </th>
              <th>Tenant</th>
              <th>Unit number</th>
              <th>Floor number</th>
              <th>Monthly rent</th>
              <th>Occupied</th>
              <th>Add Tenant</th>
            </tr>
            </thead>
            <tbody>
            {% for r in units %}
            <tr>
                <td class="p-name">
                    <a>{{r.property}}</a>
                </td>
                {% for p in r.unit_landlord.all %}
                <td class="p-name">
                    <a>{{p.name}}</a>
                </td>
                {% empty %}
                <td class="p-name">
                    <a>Ibgaro</a>
                </td>
                {% endfor %}

                <td class="p-name">
                    <a>{{r.unit_tenant.name}}</a>
                </td>

                <td class="p-name">
                    <a>{{r.unit_number}}</a>
                </td>
                <td class="p-name">
                    <a>{{r.floor_number}}</a>
                </td>
                <td class="p-name">
                    <a>{{r.monthly_rent}}</a>
                </td>
                <td class="p-name">
                  {% if r.occupied %}
                       <a>occupied</a>
                  {% else %}
                       <a>vaccant</a>
                   {% endif %}
                </td>
                <td class="p-name">
                     <a href="{% url 'property:add_tenant'  r.id %}" class="btn btn-primary btn-xs"><i
                             class="fa fa-plus"></i> Add Tenant </a>
                </td>
                {% empty %}
                <td class="p-name">
                    <a>There are no matching prperty for your query </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>
    <!-- page end-->

</div>
{% endblock %}

property/templates/property/landlord_detail.html
{% extends 'property/base.html' %}
{% load static %}
{% load humanize %}
{% block body %}



<div>
              <div class="row">
                <div class="col-md-8">
                    <section class="panel">
                        <div class="bio-graph-heading project-heading " style="background-color: #2a3542">
                            <strong> [Ibgaro Realtors Ltd ] </strong>
                        </div>
                        <div class="panel-body bio-graph-info">
                            <!--<h1>New Dashboard BS3 </h1>-->
                            <div class="row p-details">
                                <div class="bio-row">
                                    <h4><span class="bold">Landlord name </span>: {{ landlord.name }}</h4>
                                </div>
                                <div class="bio-row">
                                    <h4><span class="bold">Landlord ID or Passport</span>: {{ landlord.ID_or_Passport}}</h4>
                                </div>
                                <div class="bio-row">
                                    <h4><span class="bold">Landlord Phone No</span>:{{ landlord.Phone }}</h4>
                                </div>



A

                            </div>

                        </div>

                    </section>



                </div>

            </div>
</div>
            {% endblock %}